goals:
   goal1:
     x: -0.8
     y: 2
   goal12:
     x: 0
     y: 2
   goal13:
     x: 0.6
     y: 1.8
   goal14:
     x: 0.8
     y: 1
   goal15:
     x: 0.8
     y: 0
   goal16:
     x: 0.8
     y: -1
   goal17: 
     x: 1.78
     y: -1.90
   goal18:
     x: 1
     y: -1.9
   goal19:
     x: -0.8
     y: -1
   goal20:
     x: -1.35
     y: -1.8
   goal21:
     x: -1.75
     y: -1.88
   goal22:
     x: -0.8
     y: -1
   goal23:
     x: -0.8
     y: 0.8
   goal24:
     x: 0.2
     y: 1.5
   goal25:
     x: 1.2
     y: 0.9
   goal26:
     x: 1.68
     y: 1.75
   goal27:
     x: 1.2
     y: 0.9
   goal28:
     x: 0
     y: 2     
   goal29:
     x: -0.8
     y: 2
   goal30:
     x: -1.6
     y: 2
