path:
   goal1:
     x: -2.0
     y: 0.0
   goal10:
     x: -1.75
     y: 0.0
   goal11:
     x: -1.5
     y: 0.1
   goal12:
     x: -1.25
     y: 0.2
   goal13:
     x: -1.0
     y: 0.2
   goal14:
     x: -0.75
     y: 0.15
   goal15:
     x: -0.5
     y: 0.0
   goal16:
     x: -0.25
     y: -0.15
   goal17:
     x: 0.0
     y: -0.2
   goal18:
     x: 0.25
     y: -0.15
   goal19:
     x: 0.5
     y: 0.0
   goal2:
     x: 0.75
     y: 0.15
   goal20:
     x: 1.0
     y: 0.2
   goal21:
     x: 1.25
     y: 0.2
   goal22:
     x: 1.5
     y: 0.15 
   goal23:
     x: 1.75
     y: 0.0  
   goal24:
     x: 2.0
     y: 0.0
